default: &default
  adapter: postgresql
  encoding: unicode
  username: keerthana
  password: keerthana1
  host: localhost
  pool: 5

development:
  <<: *default
  database: todo_app_development

test:
  <<: *default
  database: todo_app_test
